# Generated by Django 2.0.2 on 2018-02-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=25)),
                ('doctor', models.CharField(max_length=25)),
                ('consultorio', models.CharField(max_length=25)),
                ('cita_fecha_hora', models.DateTimeField()),
                ('estatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_curp', models.CharField(max_length=15)),
                ('especialidad', models.CharField(max_length=50)),
                ('d_rfc', models.CharField(max_length=13)),
                ('fecha_nacimiento', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctores_Consultorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=25)),
                ('consultorio', models.CharField(max_length=25)),
                ('horario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicamento', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=50)),
                ('formula', models.CharField(max_length=50)),
                ('vida_media', models.CharField(max_length=50)),
                ('peso_mol', models.FloatField()),
                ('prescrito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos_Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=25)),
                ('id_medicamento', models.CharField(max_length=25)),
                ('fecha_expedicion', models.DateField()),
                ('resurtir', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_afiliacion', models.CharField(max_length=20)),
                ('clinica', models.IntegerField()),
                ('estatus', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('slug', models.SlugField(default='Paciente Generico', max_length=24)),
                ('p_curp', models.CharField(max_length=15)),
                ('p_fecha_nacimiento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
