# Generated by Django 2.0.2 on 2018-02-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20180220_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_clinica', models.IntegerField()),
                ('clinica', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Consultorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_consultorio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='citas',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Doctores'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pacientes'),
        ),
        migrations.AlterField(
            model_name='doctores_consultorios',
            name='consultorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Consultorios'),
        ),
        migrations.AlterField(
            model_name='doctores_consultorios',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pacientes'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Clinicas'),
        ),
    ]
