# Generated by Django 2.0.2 on 2018-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20180221_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='medicamento_name',
            field=models.CharField(default='X', max_length=50),
        ),
    ]
