# Generated by Django 2.0.2 on 2018-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_medicamentos_medicamento_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='pname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
