# Generated by Django 2.0.2 on 2018-02-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_pacientes_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='pname',
            field=models.CharField(max_length=50),
        ),
    ]
