# Generated by Django 2.0.2 on 2018-02-28 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20180223_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta_fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Sintomas', models.CharField(max_length=250)),
                ('Notas', models.CharField(max_length=250)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Citas')),
                ('medico', models.ManyToManyField(to='principal.Doctores')),
            ],
        ),
        migrations.AddField(
            model_name='consultorios',
            name='clinca',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='principal.Clinicas'),
        ),
        migrations.AddField(
            model_name='consultorios',
            name='consultorio_numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='slug',
            field=models.SlugField(default='Paciente_Generico', max_length=24),
        ),
        migrations.AddField(
            model_name='consultas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pacientes'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Medicamentos_Pacientes'),
        ),
    ]
