# Generated by Django 2.0.2 on 2018-03-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20180228_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='pname',
        ),
    ]
